name: CI
env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC
  NODE_OPTIONS: --max_old_space_size=6144
on:
  pull_request:
  push:
    branches: ['main']
  release:
    types:
      - published
      - edited
jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: sbt lint
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        java: ['temurin:11', 'temurin:17', 'temurin:21']
        scala: ['2.12.20', '2.13.16', '3.5.2']
        platform: ['JVM', 'Native', 'JS']
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v1
      with:
        jvm: ${{ matrix.java }}
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Install Bohem GC
      if: matrix.platform == 'Native'
      run: sudo apt-get update && sudo apt-get install -y libgc-dev
    - name: Run tests
      run: sbt ++${{ matrix.scala }}! test${{ matrix.platform }}
  ci:
    runs-on: ubuntu-20.04
    needs: [build,lint]
    steps:
      - run: echo "All checks passed"
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: [build,lint]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.1
      - name: Run release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
